Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "ansiblevm1"
  config.vm.define "ansiblevm1"

  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "private_network", ip: "192.168.2.2"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
	vb.name = "ansiblevm1"
    vb.memory = "512"
  end  
end
